### ISSUE TITLE
how to compile

### ISSUE THREAD

**Issue by nullified33** [True-cc/BuilderHelper#1]

**Comment by SelfMadeSystem** [comment]
You can do `gradlew build`. Please look at how to build gradle projects and if you have other issues, look at the fabric wiki. I am not a tutorial.

**Comment by nullified33** [comment]
> You can do `gradlew build`. Please look at how to build gradle projects and if you have other issues, look at the fabric wiki. I am not a tutorial.

it doesnt have a bat
