### ISSUE TITLE
Gradle Error

### ISSUE THREAD

**Issue by nullified33** [True-cc/BuilderHelper#3]
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

**Comment by nullified33** [comment]
Can you please publish a release

**Comment by SelfMadeSystem** [comment]
bro fine whatever just stop making random ass issues

**Comment by SelfMadeSystem** [comment]
https://github.com/True-cc/BuilderHelper/releases/tag/0.1

**Comment by nullified33** [comment]
> bro fine whatever just stop making random ass issues

ok

**Comment by nullified33** [comment]
> https://github.com/True-cc/BuilderHelper/releases/tag/0.1

**Comment by nullified33** [comment]
Sorry
