### ISSUE TITLE
how to compile this mod?

### ISSUE THREAD

**Issue by hjhyhg** [True-cc/BuilderHelper#4]
how do i turn this zip into a jar?

**Comment by nullified33** [comment]
what?

**Comment by hjhyhg** [comment]
> what?

 is there any tutorials?

**Comment by nullified33** [comment]
https://github.com/True-cc/BuilderHelper/releases/download/0.1/BuilderHelper-0.1.jar

**Comment by hjhyhg** [comment]
> https://github.com/True-cc/BuilderHelper/releases/download/0.1/BuilderHelper-0.1.jar

thanks
